brew "awscli" # https://aws.amazon.com/cli/
brew "bat" # https://github.com/sharkdp/bat
brew "chezmoi" # https://www.chezmoi.io/
brew "devcontainer" # https://containers.dev/
brew "direnv" # https://direnv.net/
brew "fd" # https://github.com/sharkdp/fd
brew "gh" # https://cli.github.com/
brew "git-delta" # https://github.com/dandavison/delta
brew "git-lfs" # https://git-lfs.com/
brew "lf" # https://github.com/gokcehan/lf
brew "mise" # https://mise.jdx.dev
brew "neovim" # https://neovim.io/
brew "ripgrep" # https://github.com/BurntSushi/ripgrep
brew "tlrc" # https://github.com/tldr-pages/tlrc
