brew "bat" # https://github.com/sharkdp/bat
brew "chezmoi" # https://www.chezmoi.io/
brew "direnv" # https://direnv.net/
brew "fd" # https://github.com/sharkdp/fd
brew "gh" # https://cli.github.com/
brew "lf" # https://github.com/gokcehan/lf
brew "mise" # https://mise.jdx.dev
brew "ripgrep" # https://github.com/BurntSushi/ripgrep
brew "tlrc" # https://github.com/tldr-pages/tlrc
